### ISSUE TITLE
question about a little modification

### ISSUE THREAD

**Issue by ljgdasfhk** [gjedeer/tuntox#55]
Can I replace the function ```tox_friend_send_lossless_packet``` with a ```tox_friend_send_lossy_packet```? Should I replace the packet header?

**Comment by gjedeer** [comment]
I don't think TCP retransmission will occur on a tunnel to localhost but sure, you're welcome to try. My understanding of the stack is that you're going to need to implement retransmission of lost packets yourself, which will be a big task.

Anyway: tuntox connections are stateless, the only packets that need to be lossless is create and delete tunnel, if you make other packets lossy the only thing that may stop working is the stream content itself

**Comment by ljgdasfhk** [comment]
I want to understand.
I compare your program and ```toxvpn```.
It uses ```tox_friend_send_lossy_packet``` in the file ```interface.cpp```.
There is no big task with lost packets.

Now questions:
Why do you need this
```for (i = 0; i <33;) / * 2.667 seconds per packet max * /```

what numbers should be in
data [0] = PROTOCOL_MAGIC_HIGH;
data [1] = PROTOCOL_MAGIC_LOW;
to use lossy packet instead of lossless

**Comment by gjedeer** [comment]
> Why do you need this
> for (i = 0; i <33;) / * 2.667 seconds per packet max * /

Because the "lossless" packets don't arrive sometimes, too. This is signalled by an error returned from toxcore. You wouldn't receive such an error with tox_friend_send_lossy_packet, you would have to keep timeouts for each packet you sent.

toxvpn is operating on another level - it's simulating a network card - so the kernel retransmits TCP packets if they're lost. Here' we would need to re-implement that.

Re. PROTOCOL_MAGIC*, it's an arbitrary number defined in https://github.com/gjedeer/tuntox/blob/d6a820706dea0c6e5e69ac7e5cce511ad78f640d/main.h#L28 . As far as I remember, the first byte must be greater than 0xa0. This was once documented on https://libtoxcore.so/ but the site is long gone.

**Comment by gjedeer** [comment]
Ah, found it in the sources.

https://github.com/TokTok/c-toxcore/blob/master/toxcore/net_crypto.h#L41

So for lossy packets, the ID would need to start with 0xb0.
