### ISSUE TITLE
 Act as a SOCKS5 client, so tuntox can connect over tor

### ISSUE THREAD

**Issue by emdee-is** [gjedeer/tuntox#72]
Act as a SOCKS5 client, so tuntox can connect over tor. That's much easier to add, please open a new issue if you're interested about this. There's existing support in toxcore and I'd just have to expose it using a command line switch, or read the standard SOCKS_PROXY environment variable.

(I use both iptables and torsocks, but torsocks is very limited in the system calls it allows.)

**Comment by gjedeer** [comment]
Build the code from master branch, then run:

```
ALL_PROXY=socks5://127.0.0.1:9050 ./tuntox
```

Let me know how it worked for you please.

**Comment by gjedeer** [comment]
Yeah I know http_proxy and https_proxy, but they're supposed to be used to HTTP and HTTPS connections only. So that's a no.

I'm open to changing it to socks_proxy but I have never met software which uses that. ALL_PROXY works with curl. Any examples of where socks_proxy variable is used?

Re. build:
- lsodium is (was?) automatically pulled by pkg-config. I have been building against 0.2.13. Just pulled the latest master and woah, they changed a lot in the build process. I'll build it when I have more time because the usual process fails here.
- you can `make nostatic`. For most people that i met, static binaries are a good thing.

**Comment by gjedeer** [comment]
regarding build: i have built from latest master and no problems at all, did not need to add -lsodium:

```
pkg-config --static --libs toxcore 
-L/usr/local/lib -ltoxcore -lpthread -lnsl -lrt -lsodium -pthread
```

**Comment by emdee-is** [comment]
> lsodium is (was?) automatically pulled by pkg-config. 

My fault: I  had to add lsodium because I wasn't using pkg-config.

> static binaries are a good thing

I agree they are a good thing but do most systems have them? Maybe again my fault as I have to ask my package manager for static for each one.

Ignorant Philosophical Question as I've never played with it, but as Tox runs over IPv6, why not just run Tox over onioncat? Would it not work out-of-the-box?
